### PR TITLE
fix: semantic dependency upload issue

### LINKED ISSUE #237: Semantic-hub model upload issue
### Current Behavior
When trying to upload some random model, it shows error message. 

example:
When tried to upload DigitalProductPassport:3.0.0, it throws error:
{"error":{"message":"Validation failed.","path":"/hub/api/v1/models","details":{"ERR_PROCESSING":"Resolution strategy returned a model which does not contain element definition for urn:samm:io.catenax.shared.quantity:1.0.0#LinearCharacteristic"}}}

link: https://github.com/eclipse-tractusx/sldt-semantic-models/actions/runs/8018829694/job/21905528698

### Expected Behavior
Model should be uploaded successfully, as the dependent models are already present in DB.

The issue does not occur for every model, but only for few models. 

## Issue trace:
The validation of model fails in semantic-hub side. 
SAMMSdk.java class throws error: https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java#L79
Seems something wrong with samm sdk, but not sure for now.

### PR DESCRIPTION
**Pull request by mittalVaghela**
## Description
Bug Fix:  fix semantic dependent model upload issue

### Following changes :
- Update SAMM SDK Version to 2.9.8
- Update Jena Server to 5.0.0 
- Update common-io version 2.17
- Update the validation logic according to new version
- Remove Unwanted code
- Added test case for samm dependent model validation 

## Issue:
Fixes #237

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by agg3fe** [comment]
@mittalVaghela Thanks for the updates.
IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases
It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. 
Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it.
FYI @tunacicek @jSchuetz88

**Comment by mittalVaghela** [comment]
> @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88

@Sahin


> @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88

@agg3fe Thank you for your suggestion. I will update it to the latest version, 2.9.7, and let you know once it's ready for final review.

**Comment by mittalVaghela** [comment]
> > @mittalVaghela Thanks for the updates. IMO, it makes more sense to update the samm sdk version to the latest. Here are latest versions released https://github.com/eclipse-esmf/esmf-sdk/releases It is best when semantic models repository and semantic-hub have same version. Since semantic model repo (https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh#L33) uses 2.9.7 version, so semantic-hub should also have the same version. Updating to samm sdk 2.8.1 will not be much beneficial as it will still have some issues with it. FYI @tunacicek @jSchuetz88
> 
> @agg3fe Thank you for your suggestion. I will update it to the latest version, 2.9.7, and let you know once it's ready for final review.

@agg3fe  i have updated the SAMM SDK to the latest version of ESMF (2.9.7) and Jena (5.0.0). Could you please verify this again?

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java [hunk 1]
```diff
@@ -104,79 +91,65 @@ public AspectModelUrn getAspectUrn( final Model model ) {
...
-         this.type = type;
-      }
-
-      @Override
-      public Try<Model> apply( final AspectModelUrn aspectModelUrn ) {
-         final String namespace = checkAndReplaceToBammPrefix(aspectModelUrn.getNamespace());
-         final Resource resource = ResourceFactory.createResource( checkAndReplaceToBammPrefix(aspectModelUrn.getUrn().toASCIIString()));
-         final Model model = tripleStoreRequester.apply( checkAndReplaceToBammPrefix(aspectModelUrn.getUrn().toString()));
-
-         if(!isBamm()){
```
Comment (tunacicek) [inline backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/SAMMSdk.java:141]: This check is removed- Do we not need to load the namespaces for bamm?

File: backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java [hunk 2]
```diff
@@ -967,7 +968,9 @@ public void testModelStatusUpdateByURN() throws Exception {
 
    }
 
-   @Test
+	 //issue its fix into latest jena version 4.9.0 or above
```
Comment (tunacicek) [inline backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java:971]: Why are the following tests disabled?

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java [hunk 3]
```diff
@@ -24,189 +24,135 @@
...
-      try {
-         InputStream ompCSS = getClass().getResourceAsStream( "/catena-template.css" );
-         String defaultCSS = CharStreams.toString( new InputStreamReader( ompCSS ) );
-
-         options.put( HtmlGenerationOption.STYLESHEET, defaultCSS );
-      } catch ( IOException e ) {
-         return Try.failure( e );
+       String modelData = persistenceLayer.getModelDefinition(AspectModelUrn.fromUrn(urn));
+       final AspectModel aspectModel =loadAspectModel(modelData).get();
+       final JsonSchemaGenerationConfig config = JsonSchemaGenerationConfigBuilder.builder()
```
Comment (tunacicek) [inline backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java:79]: Does it make sense to create this object one time on class init?

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java [hunk 4]
```diff
@@ -24,189 +24,135 @@
...
-         return Try.success( output.toByteArray() );
-      } catch ( IOException e ) {
-         return Try.failure( e );
-      }
-   }
 
-   public String getOpenApiDefinitionJson( String urn, String baseUrl ) {
-      Aspect aspect = getBamAspect( urn );
-      AspectModelOpenApiGenerator openApiGenerator = new AspectModelOpenApiGenerator();
+			final DocumentationGenerationConfig config = DocumentationGenerationConfigBuilder.builder()
```
Comment (tunacicek) [inline backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java:97]: Also here: 
Does it make sense to create this object one time on class init?

**Review by tunacicek — CHANGES_REQUESTED** [review]

**Comment by tunacicek** [comment]
@mittalVaghela : thanks for the PR. 
Also the https://github.com/eclipse-tractusx/sldt-semantic-hub/blob/main/README.md needs to be adjusted to describe jena 5.0.0

**Comment by tunacicek** [comment]
@mittalVaghela : You need to accept the eca -> https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/sldt-semantic-hub/309

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/TripleStoreConfiguration.java [hunk 5]
```diff
@@ -67,7 +67,6 @@ public FusekiServer fusekiServer( final TripleStoreProperties properties ) {
                          .verbose( true )
                          .contextPath( embedded.getContextPath() )
                          .enableStats( true )
-                         .enableCors( true )
```
[the remark this answers is not in the document]
Comment (mittalVaghela) [reply backend/src/main/java/org/eclipse/tractusx/semantics/hub/TripleStoreConfiguration.java:70]: ok i will revert this changes.

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java [hunk 6]
```diff
@@ -67,11 +59,11 @@ public Try<String> getExamplePayloadJson( String urn  ) {
...
 
-   public Try getAasSubmodelTemplate( String urn, AasFormat aasFormat ) {
+   public Try getAasSubmodelTemplate( String urn, AasFileFormat aasFormat ) {
       return sdkAccessHelperSAMM.getAasSubmodelTemplate( urn, aasFormat );
    }
 
-   public Try<VersionedModel> loadBammModel( String modelString ) {
-      return sdkAccessHelperSAMM.loadSammModel( modelString );
-   }
+	public Try<AspectModel> loadAspectModel(String modelUrn){
```
[the remark this answers is not in the document]
Comment (mittalVaghela) [reply backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java:66]: project inbuild

File: backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java (hunk 2 above)
Comment (mittalVaghela) [reply backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java:971]: Actully latest version of jena and  samm sdk validator it will take it as warning not as error so i comment out this test case

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java (hunk 4 above)
Comment (mittalVaghela) [reply backend/src/main/java/org/eclipse/tractusx/semantics/hub/samm/SDKAccessHelperSAMM.java:97]: config object has single use only for this method i prefer to create this object when it will required.

**Comment by agg3fe** [comment]
Hi @mittalVaghela, I just noticed one thing. The spring boot version in your local application is 3.2.4, but the latest spring boot version in tractusx repo is 3.2.5. There are some other dependencies also which are different in both pom.xml files. Could you please compare and update this in your repo and build the project again. Otherwise this might create some discrepancies in final build.
also this is important to create an IP issue for the new Restricted dependencies. That part I will handle as soon as pom.xml is updated.
Thanks

**Comment by mittalVaghela** [comment]
> Hi @mittalVaghela, I just noticed one thing. The spring boot version in your local application is 3.2.4, but the latest spring boot version in tractusx repo is 3.2.5. There are some other dependencies also which are different in both pom.xml files. Could you please compare and update this in your repo and build the project again. Otherwise this might create some discrepancies in final build. also this is important to create an IP issue for the new Restricted dependencies. That part I will handle as soon as pom.xml is updated. Thanks

sure i will

**Comment by agg3fe** [comment]
> @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.

Currently we are waiting for the approval of IP issue raised.

**Comment by mittalVaghela** [comment]
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

ok. but i updated [chart](version: "0.4.3", path: "charts/semantic-hub"))

**Comment by mittalVaghela** [comment]
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

ok.

File: charts/semantic-hub/Chart.yaml [hunk 7]
```diff
@@ -26,8 +26,8 @@ sources:
   - https://github.com/eclipse-tractusx/sldt-semantic-hub
 
 type: application
-version: 0.4.2
-appVersion: 0.5.2
+version: 0.4.3
+appVersion: 0.5.3
```
Comment (agg3fe) [inline charts/semantic-hub/Chart.yaml:30]: for now, remove changes to `appVersion` and keep only `version`. We will need to build a new version 0.5.3 after this PR is merged. will create a new PR for that.
Also please add changelog to this PR, stating the major changes this PR has.

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java [hunk 8]
```diff
@@ -67,11 +59,11 @@ public Try<String> getExamplePayloadJson( String urn  ) {
...
 
-   public Try getAasSubmodelTemplate( String urn, AasFormat aasFormat ) {
+   public Try getAasSubmodelTemplate( String urn, AasFileFormat aasFormat ) {
       return sdkAccessHelperSAMM.getAasSubmodelTemplate( urn, aasFormat );
    }
 
-   public Try<VersionedModel> loadBammModel( String modelString ) {
-      return sdkAccessHelperSAMM.loadSammModel( modelString );
-   }
+	public Try<AspectModel> loadAspectModel( String modelUrn ){
```
Comment (tunacicek) [inline backend/src/main/java/org/eclipse/tractusx/semantics/hub/SDKAccessHelper.java:66]: Code Format not correct.

File: backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java [hunk 9]
```diff
@@ -107,6 +107,7 @@ public SemanticModel getModel( final AspectModelUrn urn ) {
    @Override
    public SemanticModel updateModel( String urn, SemanticModelStatus status ) {
 
+	  validateStatusParameter(status);
```
Comment (tunacicek) [inline backend/src/main/java/org/eclipse/tractusx/semantics/hub/persistence/triplestore/TripleStorePersistence.java:110]: code format not correct

File: backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java [hunk 10]
```diff
@@ -648,9 +648,10 @@ public void testSaveModelWithExternalReferencesExpectSuccessForBAMM() throws Exc
             .andDo( MockMvcResultHandlers.print() )
             .andExpect( status().isBadRequest() )
             .andExpect( jsonPath( "$.error.message", is( "Validation failed." ) ) )
-            .andExpect( jsonPath( "$.error.details.ERR_PROCESSING",
-                  containsString( "urn:bamm:org.eclipse.tractusx.traceability:0.1.1#PartDataCharacteristic not found" ) ) );
-      // save the traceability aspect model
+				    .andExpect( jsonPath( "$.error.details.validationError",
```
Comment (tunacicek) [inline backend/src/test/java/org/eclipse/tractusx/semantics/hub/ModelsApiTest.java:651]: format?

**Comment by agg3fe** [comment]
> > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> 
> Currently we are waiting for the approval of IP issue raised.

@mittalVaghela IP issue is closed now. As soon as you fix the comments, we can merge the PR.
Also please squash the commits before we can merge it.

**Comment by mittalVaghela** [comment]
> > > @mittalVaghela IP issue for code content has been created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19064 This is important since this PR contains more than 1k lines of code.
> > 
> > 
> > Currently we are waiting for the approval of IP issue raised.
> 
> @mittalVaghela IP issue is closed now. As soon as you fix the comments, we can merge the PR. Also please squash the commits before we can merge it.

@agg3fe & @tunacicek , I have addressed all the comments and implemented the suggested changes. Please review it again and let me know if any further changes are needed. Thank you!

**Review by mittalVaghela — COMMENTED** [review]
All changes its done

**Review by agg3fe — APPROVED** [review]
LGTM
